### ISSUE TITLE
Can't add a divider in the edit/create form

### ISSUE THREAD

**Issue by pepe95270** [javiereguiluz/easy-admin-demo#30]
Hi,
I have a problem when I add `- { type: 'divider' }` in product.yml
So, my product.yml look like this:
product.yml:

``` yaml
    easy_admin:
        entities:
            Product:
                 class: AppBundle\Entity\Product
                ...
                form:
                    fields:
                        - { property: 'createdAt', label: 'Crée le', css_class: 'col-sm-4' }
                        - { type: 'divider' }
                        - { property: 'name', label: 'Nom', css_class: 'col-sm-4' }
```

But it throw an Exeption: 

> RuntimeException in NormalizerConfigPass.php line 152: One of the values of the "fields" option for the "edit" view of the "AppBundle\Entity\Product" entity does not define the "property" option.

Thank you :)
